server:
  port: 8500

eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://meng:meng@localhost:8600/eureka/

spring:
  application:
    name: dao
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/meng?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5

#  jpa:
#    show-sql: false
#    generate-ddl: true
#    hibernate.ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  jackson.date-format: yyyy-MM-dd HH:mm:ss
#  time-zone: GMT+8
